version: '3.8'

services:
  frontend:
    # uncomment the following line if you want to run a local instance of MongoDB
    # depends_on:
    #   - db
    build:
      context: .
      dockerfile: Dockerfile
    
    # do port mapping so that we can access the app from the browser
    ports:
      - 3000:3000
    
    # use docker compose to watch for changes and rebuild the container
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./next.config.js
          action: rebuild
      
        - path: .
          target: /app
          action: sync
    
    # define the environment variables
    environment:
      # we're using MongoDB atlas so we need to pass in the connection string
     NEXT_PUBLIC_SUPABASE_URL: https://wjyimkeequncdarvitza.supabase.co # Link to the Supabase service
     NEXT_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqeWlta2VlcXVuY2RhcnZpdHphIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODE1ODU0ODYsImV4cCI6MTk5NzE2MTQ4Nn0.pZJaTbahl0q2r6NNX_N9J5S2omdfBpU84_4XzXm8Uu0
     CLERK_FRONTEND_API: pk_live_Y2xlcmsubW9kZXJuZXZlbnR6LmNvbSQ
     CLERK_API_KEY: sk_live_bbBYfWdxtWpsO4d6hzXuedvfRbzY1Om8BUBz03qUqH
     NODE_ENV: production

  # we're using MongoDB atlas so we don't need to run a local instance of MongoDB
  # but if you want to run a local instance, you can do it this way
  # db:
  #   image: mongo
  #   ports:
  #     - 27017:27017
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=sujata
  #     - MONGO_INITDB_ROOT_PASSWORD=rnZzJjIDr3bIDymV
  #   volumes:
  #     - tasked:/data/db
    
volumes:
  supabase_data: